### ISSUE TITLE
Data not being pulled

### ISSUE THREAD

**Issue by jennadaly** [CT-Data-Collaborative/ctdata-edsight-cli#7]
* CTData EdSight Scraping Tool version:
* Python version:
* Operating System:

### Description

- Educator Demographics only has CT data, no district level data
- Primary Disability only has CT level data, no district level data.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by scuerda** [comment]
Resolved by f7471af888e96fdfd15a3e82b022b44fd3c5024c
