### ISSUE TITLE
Data displaying incorrectly.

### ISSUE THREAD

**Issue by jennadaly** [CT-Data-Collaborative/ctdata-edsight-cli#8]
* CTData EdSight Scraping Tool version:
* Python version:
* Operating System:

### Description

- Suspension Rates CT level data 
- All Smarter Balanced Growth Model data (district and state)
- All Staffing Levels data (district and state)
- Fitness CT level data

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by scuerda** [comment]
The suspension rate ct data is an upstream issue with EdSight. None of the subgroup variables are available when selecting State of Connecticut. I'll remove those files.

**Comment by scuerda** [comment]
Smarter Balanced was a typo in a variable name.

**Comment by scuerda** [comment]
Staffing level resolved as well.

**Comment by scuerda** [comment]
Fitness resolved as well.
